version: 2
updates:
  # 1. Go dependencies updates
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  # 2. Docker image updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  # 3. GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      